/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShiftsRouteImport } from './routes/_app.shifts'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRegularizationRouteImport } from './routes/_app.regularization'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOvertimeRouteImport } from './routes/_app.overtime'
import { Route as AppLeaveRequestsRouteImport } from './routes/_app.leave-requests'
import { Route as AppLeavePoliciesRouteImport } from './routes/_app.leave-policies'
import { Route as AppLeaveBalancesRouteImport } from './routes/_app.leave-balances'
import { Route as AppLeaveApprovalsRouteImport } from './routes/_app.leave-approvals'
import { Route as AppHolidaysRouteImport } from './routes/_app.holidays'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDesignationsRouteImport } from './routes/_app.designations'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAttendanceLogsRouteImport } from './routes/_app.attendance-logs'
import { Route as AppAttendanceApprovalsRouteImport } from './routes/_app.attendance-approvals'
import { Route as AppApplyLeaveRouteImport } from './routes/_app.apply-leave'
import { Route as AppSuperAdminUsersRouteImport } from './routes/_app.super-admin.users'
import { Route as AppSuperAdminRolesRouteImport } from './routes/_app.super-admin.roles'
import { Route as AppSuperAdminOverviewRouteImport } from './routes/_app.super-admin.overview'
import { Route as AppReportsLeaveRouteImport } from './routes/_app.reports.leave'
import { Route as AppReportsComplianceRouteImport } from './routes/_app.reports.compliance'
import { Route as AppReportsAttendanceRouteImport } from './routes/_app.reports.attendance'
import { Route as AppManagerApprovalsRouteImport } from './routes/_app.manager.approvals'
import { Route as AppIntegrationsSsoRouteImport } from './routes/_app.integrations.sso'
import { Route as AppIntegrationsPayrollRouteImport } from './routes/_app.integrations.payroll'
import { Route as AppIntegrationsHrmsRouteImport } from './routes/_app.integrations.hrms'
import { Route as AppIntegrationsBiometricRouteImport } from './routes/_app.integrations.biometric'
import { Route as AppHrShiftsRouteImport } from './routes/_app.hr.shifts'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAdminPoliciesRouteImport } from './routes/_app.admin.policies'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegularizationRoute = AppRegularizationRouteImport.update({
  id: '/regularization',
  path: '/regularization',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOvertimeRoute = AppOvertimeRouteImport.update({
  id: '/overtime',
  path: '/overtime',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsRoute = AppLeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppLeavePoliciesRoute = AppLeavePoliciesRouteImport.update({
  id: '/leave-policies',
  path: '/leave-policies',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveBalancesRoute = AppLeaveBalancesRouteImport.update({
  id: '/leave-balances',
  path: '/leave-balances',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveApprovalsRoute = AppLeaveApprovalsRouteImport.update({
  id: '/leave-approvals',
  path: '/leave-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppHolidaysRoute = AppHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignationsRoute = AppDesignationsRouteImport.update({
  id: '/designations',
  path: '/designations',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceLogsRoute = AppAttendanceLogsRouteImport.update({
  id: '/attendance-logs',
  path: '/attendance-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceApprovalsRoute = AppAttendanceApprovalsRouteImport.update({
  id: '/attendance-approvals',
  path: '/attendance-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyLeaveRoute = AppApplyLeaveRouteImport.update({
  id: '/apply-leave',
  path: '/apply-leave',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminUsersRoute = AppSuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminRolesRoute = AppSuperAdminRolesRouteImport.update({
  id: '/super-admin/roles',
  path: '/super-admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminOverviewRoute = AppSuperAdminOverviewRouteImport.update({
  id: '/super-admin/overview',
  path: '/super-admin/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsLeaveRoute = AppReportsLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsComplianceRoute = AppReportsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsAttendanceRoute = AppReportsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppManagerApprovalsRoute = AppManagerApprovalsRouteImport.update({
  id: '/manager/approvals',
  path: '/manager/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsSsoRoute = AppIntegrationsSsoRouteImport.update({
  id: '/integrations/sso',
  path: '/integrations/sso',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsPayrollRoute = AppIntegrationsPayrollRouteImport.update({
  id: '/integrations/payroll',
  path: '/integrations/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsHrmsRoute = AppIntegrationsHrmsRouteImport.update({
  id: '/integrations/hrms',
  path: '/integrations/hrms',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsBiometricRoute =
  AppIntegrationsBiometricRouteImport.update({
    id: '/integrations/biometric',
    path: '/integrations/biometric',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrShiftsRoute = AppHrShiftsRouteImport.update({
  id: '/hr/shifts',
  path: '/hr/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPoliciesRoute = AppAdminPoliciesRouteImport.update({
  id: '/admin/policies',
  path: '/admin/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apply-leave': typeof AppApplyLeaveRoute
  '/attendance-approvals': typeof AppAttendanceApprovalsRoute
  '/attendance-logs': typeof AppAttendanceLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/designations': typeof AppDesignationsRoute
  '/employees': typeof AppEmployeesRoute
  '/holidays': typeof AppHolidaysRoute
  '/leave-approvals': typeof AppLeaveApprovalsRoute
  '/leave-balances': typeof AppLeaveBalancesRoute
  '/leave-policies': typeof AppLeavePoliciesRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/overtime': typeof AppOvertimeRoute
  '/profile': typeof AppProfileRoute
  '/regularization': typeof AppRegularizationRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/hr/shifts': typeof AppHrShiftsRoute
  '/integrations/biometric': typeof AppIntegrationsBiometricRoute
  '/integrations/hrms': typeof AppIntegrationsHrmsRoute
  '/integrations/payroll': typeof AppIntegrationsPayrollRoute
  '/integrations/sso': typeof AppIntegrationsSsoRoute
  '/manager/approvals': typeof AppManagerApprovalsRoute
  '/reports/attendance': typeof AppReportsAttendanceRoute
  '/reports/compliance': typeof AppReportsComplianceRoute
  '/reports/leave': typeof AppReportsLeaveRoute
  '/super-admin/overview': typeof AppSuperAdminOverviewRoute
  '/super-admin/roles': typeof AppSuperAdminRolesRoute
  '/super-admin/users': typeof AppSuperAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apply-leave': typeof AppApplyLeaveRoute
  '/attendance-approvals': typeof AppAttendanceApprovalsRoute
  '/attendance-logs': typeof AppAttendanceLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/designations': typeof AppDesignationsRoute
  '/employees': typeof AppEmployeesRoute
  '/holidays': typeof AppHolidaysRoute
  '/leave-approvals': typeof AppLeaveApprovalsRoute
  '/leave-balances': typeof AppLeaveBalancesRoute
  '/leave-policies': typeof AppLeavePoliciesRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/overtime': typeof AppOvertimeRoute
  '/profile': typeof AppProfileRoute
  '/regularization': typeof AppRegularizationRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/hr/shifts': typeof AppHrShiftsRoute
  '/integrations/biometric': typeof AppIntegrationsBiometricRoute
  '/integrations/hrms': typeof AppIntegrationsHrmsRoute
  '/integrations/payroll': typeof AppIntegrationsPayrollRoute
  '/integrations/sso': typeof AppIntegrationsSsoRoute
  '/manager/approvals': typeof AppManagerApprovalsRoute
  '/reports/attendance': typeof AppReportsAttendanceRoute
  '/reports/compliance': typeof AppReportsComplianceRoute
  '/reports/leave': typeof AppReportsLeaveRoute
  '/super-admin/overview': typeof AppSuperAdminOverviewRoute
  '/super-admin/roles': typeof AppSuperAdminRolesRoute
  '/super-admin/users': typeof AppSuperAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/apply-leave': typeof AppApplyLeaveRoute
  '/_app/attendance-approvals': typeof AppAttendanceApprovalsRoute
  '/_app/attendance-logs': typeof AppAttendanceLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/designations': typeof AppDesignationsRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/holidays': typeof AppHolidaysRoute
  '/_app/leave-approvals': typeof AppLeaveApprovalsRoute
  '/_app/leave-balances': typeof AppLeaveBalancesRoute
  '/_app/leave-policies': typeof AppLeavePoliciesRoute
  '/_app/leave-requests': typeof AppLeaveRequestsRoute
  '/_app/overtime': typeof AppOvertimeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/regularization': typeof AppRegularizationRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/policies': typeof AppAdminPoliciesRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/hr/shifts': typeof AppHrShiftsRoute
  '/_app/integrations/biometric': typeof AppIntegrationsBiometricRoute
  '/_app/integrations/hrms': typeof AppIntegrationsHrmsRoute
  '/_app/integrations/payroll': typeof AppIntegrationsPayrollRoute
  '/_app/integrations/sso': typeof AppIntegrationsSsoRoute
  '/_app/manager/approvals': typeof AppManagerApprovalsRoute
  '/_app/reports/attendance': typeof AppReportsAttendanceRoute
  '/_app/reports/compliance': typeof AppReportsComplianceRoute
  '/_app/reports/leave': typeof AppReportsLeaveRoute
  '/_app/super-admin/overview': typeof AppSuperAdminOverviewRoute
  '/_app/super-admin/roles': typeof AppSuperAdminRolesRoute
  '/_app/super-admin/users': typeof AppSuperAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/apply-leave'
    | '/attendance-approvals'
    | '/attendance-logs'
    | '/dashboard'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/holidays'
    | '/leave-approvals'
    | '/leave-balances'
    | '/leave-policies'
    | '/leave-requests'
    | '/overtime'
    | '/profile'
    | '/regularization'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/shifts'
    | '/admin/audit'
    | '/admin/policies'
    | '/admin/roles'
    | '/admin/users'
    | '/hr/shifts'
    | '/integrations/biometric'
    | '/integrations/hrms'
    | '/integrations/payroll'
    | '/integrations/sso'
    | '/manager/approvals'
    | '/reports/attendance'
    | '/reports/compliance'
    | '/reports/leave'
    | '/super-admin/overview'
    | '/super-admin/roles'
    | '/super-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/apply-leave'
    | '/attendance-approvals'
    | '/attendance-logs'
    | '/dashboard'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/holidays'
    | '/leave-approvals'
    | '/leave-balances'
    | '/leave-policies'
    | '/leave-requests'
    | '/overtime'
    | '/profile'
    | '/regularization'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/shifts'
    | '/admin/audit'
    | '/admin/policies'
    | '/admin/roles'
    | '/admin/users'
    | '/hr/shifts'
    | '/integrations/biometric'
    | '/integrations/hrms'
    | '/integrations/payroll'
    | '/integrations/sso'
    | '/manager/approvals'
    | '/reports/attendance'
    | '/reports/compliance'
    | '/reports/leave'
    | '/super-admin/overview'
    | '/super-admin/roles'
    | '/super-admin/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/apply-leave'
    | '/_app/attendance-approvals'
    | '/_app/attendance-logs'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/designations'
    | '/_app/employees'
    | '/_app/holidays'
    | '/_app/leave-approvals'
    | '/_app/leave-balances'
    | '/_app/leave-policies'
    | '/_app/leave-requests'
    | '/_app/overtime'
    | '/_app/profile'
    | '/_app/regularization'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/shifts'
    | '/_app/admin/audit'
    | '/_app/admin/policies'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/hr/shifts'
    | '/_app/integrations/biometric'
    | '/_app/integrations/hrms'
    | '/_app/integrations/payroll'
    | '/_app/integrations/sso'
    | '/_app/manager/approvals'
    | '/_app/reports/attendance'
    | '/_app/reports/compliance'
    | '/_app/reports/leave'
    | '/_app/super-admin/overview'
    | '/_app/super-admin/roles'
    | '/_app/super-admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regularization': {
      id: '/_app/regularization'
      path: '/regularization'
      fullPath: '/regularization'
      preLoaderRoute: typeof AppRegularizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overtime': {
      id: '/_app/overtime'
      path: '/overtime'
      fullPath: '/overtime'
      preLoaderRoute: typeof AppOvertimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-requests': {
      id: '/_app/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof AppLeaveRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-policies': {
      id: '/_app/leave-policies'
      path: '/leave-policies'
      fullPath: '/leave-policies'
      preLoaderRoute: typeof AppLeavePoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-balances': {
      id: '/_app/leave-balances'
      path: '/leave-balances'
      fullPath: '/leave-balances'
      preLoaderRoute: typeof AppLeaveBalancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-approvals': {
      id: '/_app/leave-approvals'
      path: '/leave-approvals'
      fullPath: '/leave-approvals'
      preLoaderRoute: typeof AppLeaveApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holidays': {
      id: '/_app/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AppHolidaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/designations': {
      id: '/_app/designations'
      path: '/designations'
      fullPath: '/designations'
      preLoaderRoute: typeof AppDesignationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-logs': {
      id: '/_app/attendance-logs'
      path: '/attendance-logs'
      fullPath: '/attendance-logs'
      preLoaderRoute: typeof AppAttendanceLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-approvals': {
      id: '/_app/attendance-approvals'
      path: '/attendance-approvals'
      fullPath: '/attendance-approvals'
      preLoaderRoute: typeof AppAttendanceApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply-leave': {
      id: '/_app/apply-leave'
      path: '/apply-leave'
      fullPath: '/apply-leave'
      preLoaderRoute: typeof AppApplyLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/users': {
      id: '/_app/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AppSuperAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/roles': {
      id: '/_app/super-admin/roles'
      path: '/super-admin/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof AppSuperAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/overview': {
      id: '/_app/super-admin/overview'
      path: '/super-admin/overview'
      fullPath: '/super-admin/overview'
      preLoaderRoute: typeof AppSuperAdminOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/leave': {
      id: '/_app/reports/leave'
      path: '/leave'
      fullPath: '/reports/leave'
      preLoaderRoute: typeof AppReportsLeaveRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/compliance': {
      id: '/_app/reports/compliance'
      path: '/compliance'
      fullPath: '/reports/compliance'
      preLoaderRoute: typeof AppReportsComplianceRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/attendance': {
      id: '/_app/reports/attendance'
      path: '/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof AppReportsAttendanceRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/manager/approvals': {
      id: '/_app/manager/approvals'
      path: '/manager/approvals'
      fullPath: '/manager/approvals'
      preLoaderRoute: typeof AppManagerApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/sso': {
      id: '/_app/integrations/sso'
      path: '/integrations/sso'
      fullPath: '/integrations/sso'
      preLoaderRoute: typeof AppIntegrationsSsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/payroll': {
      id: '/_app/integrations/payroll'
      path: '/integrations/payroll'
      fullPath: '/integrations/payroll'
      preLoaderRoute: typeof AppIntegrationsPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/hrms': {
      id: '/_app/integrations/hrms'
      path: '/integrations/hrms'
      fullPath: '/integrations/hrms'
      preLoaderRoute: typeof AppIntegrationsHrmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/biometric': {
      id: '/_app/integrations/biometric'
      path: '/integrations/biometric'
      fullPath: '/integrations/biometric'
      preLoaderRoute: typeof AppIntegrationsBiometricRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/shifts': {
      id: '/_app/hr/shifts'
      path: '/hr/shifts'
      fullPath: '/hr/shifts'
      preLoaderRoute: typeof AppHrShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/policies': {
      id: '/_app/admin/policies'
      path: '/admin/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AppAdminPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsAttendanceRoute: typeof AppReportsAttendanceRoute
  AppReportsComplianceRoute: typeof AppReportsComplianceRoute
  AppReportsLeaveRoute: typeof AppReportsLeaveRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsAttendanceRoute: AppReportsAttendanceRoute,
  AppReportsComplianceRoute: AppReportsComplianceRoute,
  AppReportsLeaveRoute: AppReportsLeaveRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppApplyLeaveRoute: typeof AppApplyLeaveRoute
  AppAttendanceApprovalsRoute: typeof AppAttendanceApprovalsRoute
  AppAttendanceLogsRoute: typeof AppAttendanceLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppDesignationsRoute: typeof AppDesignationsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppHolidaysRoute: typeof AppHolidaysRoute
  AppLeaveApprovalsRoute: typeof AppLeaveApprovalsRoute
  AppLeaveBalancesRoute: typeof AppLeaveBalancesRoute
  AppLeavePoliciesRoute: typeof AppLeavePoliciesRoute
  AppLeaveRequestsRoute: typeof AppLeaveRequestsRoute
  AppOvertimeRoute: typeof AppOvertimeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRegularizationRoute: typeof AppRegularizationRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminPoliciesRoute: typeof AppAdminPoliciesRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppHrShiftsRoute: typeof AppHrShiftsRoute
  AppIntegrationsBiometricRoute: typeof AppIntegrationsBiometricRoute
  AppIntegrationsHrmsRoute: typeof AppIntegrationsHrmsRoute
  AppIntegrationsPayrollRoute: typeof AppIntegrationsPayrollRoute
  AppIntegrationsSsoRoute: typeof AppIntegrationsSsoRoute
  AppManagerApprovalsRoute: typeof AppManagerApprovalsRoute
  AppSuperAdminOverviewRoute: typeof AppSuperAdminOverviewRoute
  AppSuperAdminRolesRoute: typeof AppSuperAdminRolesRoute
  AppSuperAdminUsersRoute: typeof AppSuperAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplyLeaveRoute: AppApplyLeaveRoute,
  AppAttendanceApprovalsRoute: AppAttendanceApprovalsRoute,
  AppAttendanceLogsRoute: AppAttendanceLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppDesignationsRoute: AppDesignationsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppHolidaysRoute: AppHolidaysRoute,
  AppLeaveApprovalsRoute: AppLeaveApprovalsRoute,
  AppLeaveBalancesRoute: AppLeaveBalancesRoute,
  AppLeavePoliciesRoute: AppLeavePoliciesRoute,
  AppLeaveRequestsRoute: AppLeaveRequestsRoute,
  AppOvertimeRoute: AppOvertimeRoute,
  AppProfileRoute: AppProfileRoute,
  AppRegularizationRoute: AppRegularizationRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminPoliciesRoute: AppAdminPoliciesRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppHrShiftsRoute: AppHrShiftsRoute,
  AppIntegrationsBiometricRoute: AppIntegrationsBiometricRoute,
  AppIntegrationsHrmsRoute: AppIntegrationsHrmsRoute,
  AppIntegrationsPayrollRoute: AppIntegrationsPayrollRoute,
  AppIntegrationsSsoRoute: AppIntegrationsSsoRoute,
  AppManagerApprovalsRoute: AppManagerApprovalsRoute,
  AppSuperAdminOverviewRoute: AppSuperAdminOverviewRoute,
  AppSuperAdminRolesRoute: AppSuperAdminRolesRoute,
  AppSuperAdminUsersRoute: AppSuperAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
